spring.datasource.url=${DATA_URL}
spring.datasource.username=${DATA_USER}
spring.datasource.password=${DATA_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
api.security.token.secret=${{JWT_SECRET}}
AWS_ACCESS_KEY_ID=${ACCESS_KEY_ID}
AWS_SECRET_ACCESS_KEY=${SECRET_ACCESS_KEY}
AWS_REGION=us-east-1
AWS_BUCKET_NAME=${BUCKET_NAME}
